# Generated by Django 2.0.1 on 2018-01-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='post',
            new_name='content',
        ),
    ]
